### ISSUE TITLE
Issue authenticating with LLAT

### ISSUE THREAD

**Issue by artmg** [home-assistant/scenegen#9]
I am trying out scenegen, but following [prevailing wisdom on Authentication](https://www.home-assistant.io/docs/authentication/providers/) I have created a Long Lived Access Token (LLAT) in my profile instead of a system-wide API-key. I get **Error 111 Connection refused**

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
```

I will try tweaking the code to use the HTTP Header Authorization: BEARER <key> as per https://developers.home-assistant.io/docs/en/auth_api.html#example-python to see if this resolves it, otherwise I might have to use the old api-key approach for now (and slap my own wrist ;)

**Comment by artmg** [comment]
I have written and tested a fix for this, signed the CLA and submitted the PR. Thanks!
